/*
 * File:        pa2Globals.c
 * Description: Define global variables to calculate the offsets of members
 *              within structs.
 *
 * XXX DO NOT EDIT THIS FILE
 *
 */

#include <time.h>
#include <stddef.h> /* for offsetof() MACRO */
#include "pa2.h"

/* The struct tInfo gives calendar time. */
size_t tInfo_hourOffset = offsetof( struct tInfo, tm_hour );

size_t tInfo_minOffset = offsetof( struct tInfo, tm_min );

size_t tInfo_secOffset = offsetof( struct tInfo, tm_sec );

size_t tInfo_ampmOffset = offsetof( struct tInfo, am_pm );

/* Offsets into the struct tm */
size_t tm_hour_offset = offsetof( struct tm, tm_hour );

size_t tm_min_offset = offsetof( struct tm, tm_min );

size_t tm_sec_offset = offsetof( struct tm, tm_sec );
