/*
 * File: pa2Strings.h
 * Description: Header file containing strings that are displayed to the user.
 *
 * XXX DO NOT EDIT THIS FILE
 *
 */

#ifndef PA2_STRINGS_H
#define PA2_STRINGS_H

#define STR_USAGE "\nUsage: %s [numTicks [startTime]] | [--help]\n"\
"    numTicks  -- (optional) number of clock ticks to display\n"\
"                 Must be within the range of [%d-%d]\n"\
"                 Default number of ticks is %d\n"\
"    startTime -- (optional) starting time of the clock entered as HH:MM:SS"\
                  "(A|a|P|p)\n"\
"                 HH must be within the range of [%d-%d]\n"\
"                 MM must be within the range of [%d-%d]\n"\
"                 SS must be within the range of [%d-%d]\n"\
"                 (A|a|P|p) one option must be specified\n"\
"                 Default start time is the current time\n\n"

#define STR_HELP "--help" /* Used to check if the user entered --help */

/*
 * Time output strings
 */
#define STR_DEF_TIME "%s\n" /* use this string to display time when
                             * argc != MAX_ARGS */

#define STR_BCD_TIME "%02x " /* use this string to display the time
                              * after each tick */


/*
 * Error strings
 */
#define STR_TIME_RANGE_ERR   "\tOne or more time values are not within range\n"
#define STR_TIME_PARSE_ERR   "\tOne or more time values are not valid numbers\n"
#define STR_TIME_FORMAT_ERR  "\tStarting time must be formatted as HH:MM:SS"\
                             "(A|a|P|p)\n"
#define STR_TICK_PARSE_ERR   "\tError parsing number of clock ticks\n"
#define STR_TICKS_RANGE_ERR  "\tNumber of clock ticks %d not within range "\
                             "[%d-%d]\n"

/*
 * EXTRA CREDIT
 */
#define DING      "Ding!"
#define DONG      "Dong!"
#define STR_USAGE_EC "\nUsage: %s [numTicks [startTime]] | [--help]\n"\
"    numTicks  -- (optional) number of clock ticks to display\n"\
"                 Must be within the range of [%d-%d]\n"\
"                 Default number of ticks is %d\n"\
"    startTime -- (optional) starting time of the clock entered as HH:MM:SS\n"\
"                 HH must be within the range of [%d-%d]\n"\
"                 MM must be within the range of [%d-%d]\n"\
"                 SS must be within the range of [%d-%d]\n"\
"                 Default start time is the current time\n\n"


#endif /* PA2_STRINGS_H */
