/*
 * File: timeRightNow.c
 * Description: Gets the current time.
 * 
 * XXX DO NOT EDIT THIS FILE
 *
 */
#include <sys/time.h>

/*
 * Function Name: timeRightNow()
 * Prototype: int timeRightNow( struct timeval * tp, void * p );
 * Parameters:  tp -- struct timeval to be populated with the number of seconds
 *                    since January 1, 1970 (gettimeofday() does this)
 *              p  -- timezone pointer (gettimeofday() ignores this parameter,
 *                    so we should just pass in a null pointer for this)
 * Side Effects: tp is populated with the number of seconds since January 1, 
 *               1970.
 * Error Conditions: If gettimeofday() encounters an error, it returns -1 and 
 *                   sets errno (for this assignment you don't need to worry 
 *                   about any errors returned from this function).
 * Return Value: 0 on success, -1 on failure.
 */
int timeRightNow( struct timeval *tp, void *p ) {
  return gettimeofday( tp, p );
}
